sonar.organization=dflippojr
sonar.projectKey=dflippojr_music-discovery
sonar.projectName=music-discovery
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/.venv/**,**/venv/**,**/__pycache__/**,**/.pytest_cache/**,**/.ruff_cache/**,**/.mypy_cache/**,**/.cache/**,data/**
sonar.test.exclusions=**/.venv/**,**/venv/**,**/__pycache__/**,**/.pytest_cache/**,**/.ruff_cache/**,**/.mypy_cache/**,**/.cache/**,data/**
